spring:
  application:
    name: WINTER
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
server:
  port: 8089
  servlet:
    context-path: /winter
    session:
      timeout: 60m
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-sit.xxx.com/eureka/
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3

rocketmq:
  consumer:
    consumeMessageBatchMaxSize: 1 #设置一次消费消息的条数，默认为1条
    consumeThreadMax: 64
    consumeThreadMin: 20
    groupName: ${spring.application.name}
    isOnOff: 'on' #该应用是否启用消费者
    namesrvAddr: 127.0.0.1:9876
    topics: DemoTopic;  #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
  producer:
    groupName: ${spring.application.name}  #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    isOnOff: 'on' #该应用是否启用生产者
    maxMessageSize: 4096  #消息最大长度(KB)
    namesrvAddr: 127.0.0.1:9876   #mq的nameServer地址
    retryTimesWhenSendFailed: 2  #发送消息失败重试次数，默认2
    sendMsgTimeout: 3000  #发送消息超时时间,默认3000
