spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unexadmin_local_develop?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456